### ISSUE TITLE
After upgrading ESRI/Loader from 2.5.0  to 3.6, Querytask.js library file is returning 404 error

### ISSUE THREAD

**Issue by krishmandali** [Esri/esri-loader#298]
After upgrading ESRI loader to 3.6, while loading the map querytask.js is returning 404 error. Here is the error from console.
**Failed to load resource: the server responded with a status of 404 ()
QueryTask.js:1          Failed to load resource: the server responded with a status of 404 ()
ag-grid-community.cjs.js:25674 ag-Grid: tried to call sizeColumnsToFit() but the grid is coming back with zero width, maybe the grid is not visible yet on the screen?
push../node_modules/ag-grid-community/dist/ag-grid-community.cjs.js.GridPanel.sizeColumnsToFit @ ag-grid-community.cjs.js:25674
(index):25 Error: scriptError: https://js.arcgis.com/4.24/esri/tasks/support/Query.js
    at u ((index):6:38)
    at HTMLScriptElement.<anonymous> ((index):24:428)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399:1)
    at Object.onInvokeTask (core.js:41686:1)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398:1)
    at Zone.runTask (zone-evergreen.js:167:1)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:480:1)
    at invokeTask (zone-evergreen.js:1621:1)
    at HTMLScriptElement.globalZoneAwareCallback (zone-evergreen.js:1647:1)**

**Comment by odoe** [comment]
Tasks based classes were deprecated at 4.20 and removed at 4.24
https://developers.arcgis.com/javascript/latest/release-notes/#breaking-changes

The support classes are now under `esri/rest/support`

**Comment by andygup** [comment]
Closing as answered.
